### ISSUE TITLE
Aufrufsystem ohne Praxissystem

### ISSUE THREAD

**Issue by unlimited95** [crispinus2/pyeas#1]
Hallo, gibt es eine Möglichkeit das ganze auch ohne Praxissystem zu nutzen? Der Server läuft und alles funktioniert. Ich suche nun nach einer Möglichkeit direkt über die control Page, Nummern eingeben zu können, die dann in der Wartezimmer.html angezeigt werden. Also ohne ein weiteres System. Hast du da einen Tipp oder eine Idee?

Also im Prinzip sollen in der Wartezimmer.html auch die Zimmer abgebildet werden, wie in der Control, sodass man sieht, welches Zimmer besetzt ist oder frei ist. Und zusätzlich sollte man über die Control, Nummern eingeben können, die dann in der Wartezimmer.html aufgerufen werden. 

Vielleicht hast du ja eine Idee oder einen Tipp, ansonsten kein Problem. Wollte mal gefragt haben.

**Comment by crispinus2** [comment]
Hallo,
das kann man natürlich realisieren, allerdings ist dies keine Funktion des Webinterfaces. Es gibt hier: https://github.com/crispinus2/pyeas/blob/master/clients/eas-populate-room.py den Quellcode des Clients, der normalerweise GDT-Dateien als Eingabe nimmt und dann den Server anweist, den enthaltenen Patienten auf die Warteliste zu setzen.
Man könnte nun entweder auf irgendeinem Weg eine passende GDT-Datei erzeugen und sie dem Clientskript füttern, oder man könnte das Clientskript so umstricken, dass es die notwendigen Parameter direkt als Kommandozeilenargumente akzeptiert.
Auch das Webinterface wäre sicherlich mit relativ wenig Aufwand wie gewünscht zu erweitern, wir haben hier aber keinen Usecase dafür, sodass ich das nicht selbst tun würde. Ich wäre aber gern bereit, mir einen entsprechenden PR anzuschauen und ihn ggf. ins Projekt zu mergen.

**Comment by unlimited95** [comment]
Hallo, vielen Dank für die schnelle Rückmeldung! Bin relativ neu dabei, was diese Sachen betrifft, daher wird es bestimmt schwierig werden, das ganze so umzubauen, aber mal schauen vielleicht klappt es ja irgendwann. Danke auf jeden Fall für die Rückmeldung!
